name: Enforce Official Sources

on:
  push:
    branches: [ main, development ]
    paths: 
      - 'src/data/level5-*.ts'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/data/level5-*.ts'

jobs:
  enforce-official-sources:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Enforce Official Sources
      run: npm run enforce-official-sources
      
    - name: Check for blocked operations
      run: |
        if [ -f "logs/ai-blocked-operations.json" ]; then
          echo "AI operations blocked - missing official sources"
          cat logs/ai-blocked-operations.json
          exit 1
        fi
        
    - name: Upload compliance report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: compliance-report
        path: reports/official-source-compliance.json 